/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.arthurchan35.wcse.service.base;

import aQute.bnd.annotation.ProviderType;

import com.arthurchan35.wcse.model.Pages;
import com.arthurchan35.wcse.service.PagesLocalService;
import com.arthurchan35.wcse.service.persistence.PagesPersistence;
import com.arthurchan35.wcse.service.persistence.WordsPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the pages local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.arthurchan35.wcse.service.impl.PagesLocalServiceImpl}.
 * </p>
 *
 * @author Arthur Chan
 * @see com.arthurchan35.wcse.service.impl.PagesLocalServiceImpl
 * @see com.arthurchan35.wcse.service.PagesLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class PagesLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements PagesLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.arthurchan35.wcse.service.PagesLocalServiceUtil} to access the pages local service.
	 */

	/**
	 * Adds the pages to the database. Also notifies the appropriate model listeners.
	 *
	 * @param pages the pages
	 * @return the pages that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Pages addPages(Pages pages) {
		pages.setNew(true);

		return pagesPersistence.update(pages);
	}

	/**
	 * Creates a new pages with the primary key. Does not add the pages to the database.
	 *
	 * @param url_id the primary key for the new pages
	 * @return the new pages
	 */
	@Override
	public Pages createPages(long url_id) {
		return pagesPersistence.create(url_id);
	}

	/**
	 * Deletes the pages with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param url_id the primary key of the pages
	 * @return the pages that was removed
	 * @throws PortalException if a pages with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Pages deletePages(long url_id) throws PortalException {
		return pagesPersistence.remove(url_id);
	}

	/**
	 * Deletes the pages from the database. Also notifies the appropriate model listeners.
	 *
	 * @param pages the pages
	 * @return the pages that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Pages deletePages(Pages pages) {
		return pagesPersistence.remove(pages);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Pages.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return pagesPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.arthurchan35.wcse.model.impl.PagesModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return pagesPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.arthurchan35.wcse.model.impl.PagesModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return pagesPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return pagesPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return pagesPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Pages fetchPages(long url_id) {
		return pagesPersistence.fetchByPrimaryKey(url_id);
	}

	/**
	 * Returns the pages with the primary key.
	 *
	 * @param url_id the primary key of the pages
	 * @return the pages
	 * @throws PortalException if a pages with the primary key could not be found
	 */
	@Override
	public Pages getPages(long url_id) throws PortalException {
		return pagesPersistence.findByPrimaryKey(url_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(pagesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Pages.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("url_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(pagesLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Pages.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("url_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(pagesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Pages.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("url_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return pagesLocalService.deletePages((Pages)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return pagesPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the pageses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.arthurchan35.wcse.model.impl.PagesModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of pageses
	 * @param end the upper bound of the range of pageses (not inclusive)
	 * @return the range of pageses
	 */
	@Override
	public List<Pages> getPageses(int start, int end) {
		return pagesPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of pageses.
	 *
	 * @return the number of pageses
	 */
	@Override
	public int getPagesesCount() {
		return pagesPersistence.countAll();
	}

	/**
	 * Updates the pages in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param pages the pages
	 * @return the pages that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Pages updatePages(Pages pages) {
		return pagesPersistence.update(pages);
	}

	/**
	 * Returns the pages local service.
	 *
	 * @return the pages local service
	 */
	public PagesLocalService getPagesLocalService() {
		return pagesLocalService;
	}

	/**
	 * Sets the pages local service.
	 *
	 * @param pagesLocalService the pages local service
	 */
	public void setPagesLocalService(PagesLocalService pagesLocalService) {
		this.pagesLocalService = pagesLocalService;
	}

	/**
	 * Returns the pages persistence.
	 *
	 * @return the pages persistence
	 */
	public PagesPersistence getPagesPersistence() {
		return pagesPersistence;
	}

	/**
	 * Sets the pages persistence.
	 *
	 * @param pagesPersistence the pages persistence
	 */
	public void setPagesPersistence(PagesPersistence pagesPersistence) {
		this.pagesPersistence = pagesPersistence;
	}

	/**
	 * Returns the words local service.
	 *
	 * @return the words local service
	 */
	public com.arthurchan35.wcse.service.WordsLocalService getWordsLocalService() {
		return wordsLocalService;
	}

	/**
	 * Sets the words local service.
	 *
	 * @param wordsLocalService the words local service
	 */
	public void setWordsLocalService(
		com.arthurchan35.wcse.service.WordsLocalService wordsLocalService) {
		this.wordsLocalService = wordsLocalService;
	}

	/**
	 * Returns the words persistence.
	 *
	 * @return the words persistence
	 */
	public WordsPersistence getWordsPersistence() {
		return wordsPersistence;
	}

	/**
	 * Sets the words persistence.
	 *
	 * @param wordsPersistence the words persistence
	 */
	public void setWordsPersistence(WordsPersistence wordsPersistence) {
		this.wordsPersistence = wordsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.arthurchan35.wcse.model.Pages",
			pagesLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.arthurchan35.wcse.model.Pages");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PagesLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Pages.class;
	}

	protected String getModelClassName() {
		return Pages.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = pagesPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = PagesLocalService.class)
	protected PagesLocalService pagesLocalService;
	@BeanReference(type = PagesPersistence.class)
	protected PagesPersistence pagesPersistence;
	@BeanReference(type = com.arthurchan35.wcse.service.WordsLocalService.class)
	protected com.arthurchan35.wcse.service.WordsLocalService wordsLocalService;
	@BeanReference(type = WordsPersistence.class)
	protected WordsPersistence wordsPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}