/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.arthurchan35.wcse.service.base;

import com.arthurchan35.wcse.model.Words;
import com.arthurchan35.wcse.service.WordsService;
import com.arthurchan35.wcse.service.persistence.PagesPersistence;
import com.arthurchan35.wcse.service.persistence.WordsPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the words remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.arthurchan35.wcse.service.impl.WordsServiceImpl}.
 * </p>
 *
 * @author Arthur Chan
 * @see com.arthurchan35.wcse.service.impl.WordsServiceImpl
 * @see com.arthurchan35.wcse.service.WordsServiceUtil
 * @generated
 */
public abstract class WordsServiceBaseImpl extends BaseServiceImpl
	implements WordsService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.arthurchan35.wcse.service.WordsServiceUtil} to access the words remote service.
	 */

	/**
	 * Returns the pages local service.
	 *
	 * @return the pages local service
	 */
	public com.arthurchan35.wcse.service.PagesLocalService getPagesLocalService() {
		return pagesLocalService;
	}

	/**
	 * Sets the pages local service.
	 *
	 * @param pagesLocalService the pages local service
	 */
	public void setPagesLocalService(
		com.arthurchan35.wcse.service.PagesLocalService pagesLocalService) {
		this.pagesLocalService = pagesLocalService;
	}

	/**
	 * Returns the pages remote service.
	 *
	 * @return the pages remote service
	 */
	public com.arthurchan35.wcse.service.PagesService getPagesService() {
		return pagesService;
	}

	/**
	 * Sets the pages remote service.
	 *
	 * @param pagesService the pages remote service
	 */
	public void setPagesService(
		com.arthurchan35.wcse.service.PagesService pagesService) {
		this.pagesService = pagesService;
	}

	/**
	 * Returns the pages persistence.
	 *
	 * @return the pages persistence
	 */
	public PagesPersistence getPagesPersistence() {
		return pagesPersistence;
	}

	/**
	 * Sets the pages persistence.
	 *
	 * @param pagesPersistence the pages persistence
	 */
	public void setPagesPersistence(PagesPersistence pagesPersistence) {
		this.pagesPersistence = pagesPersistence;
	}

	/**
	 * Returns the words local service.
	 *
	 * @return the words local service
	 */
	public com.arthurchan35.wcse.service.WordsLocalService getWordsLocalService() {
		return wordsLocalService;
	}

	/**
	 * Sets the words local service.
	 *
	 * @param wordsLocalService the words local service
	 */
	public void setWordsLocalService(
		com.arthurchan35.wcse.service.WordsLocalService wordsLocalService) {
		this.wordsLocalService = wordsLocalService;
	}

	/**
	 * Returns the words remote service.
	 *
	 * @return the words remote service
	 */
	public WordsService getWordsService() {
		return wordsService;
	}

	/**
	 * Sets the words remote service.
	 *
	 * @param wordsService the words remote service
	 */
	public void setWordsService(WordsService wordsService) {
		this.wordsService = wordsService;
	}

	/**
	 * Returns the words persistence.
	 *
	 * @return the words persistence
	 */
	public WordsPersistence getWordsPersistence() {
		return wordsPersistence;
	}

	/**
	 * Sets the words persistence.
	 *
	 * @param wordsPersistence the words persistence
	 */
	public void setWordsPersistence(WordsPersistence wordsPersistence) {
		this.wordsPersistence = wordsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return WordsService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Words.class;
	}

	protected String getModelClassName() {
		return Words.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = wordsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.arthurchan35.wcse.service.PagesLocalService.class)
	protected com.arthurchan35.wcse.service.PagesLocalService pagesLocalService;
	@BeanReference(type = com.arthurchan35.wcse.service.PagesService.class)
	protected com.arthurchan35.wcse.service.PagesService pagesService;
	@BeanReference(type = PagesPersistence.class)
	protected PagesPersistence pagesPersistence;
	@BeanReference(type = com.arthurchan35.wcse.service.WordsLocalService.class)
	protected com.arthurchan35.wcse.service.WordsLocalService wordsLocalService;
	@BeanReference(type = WordsService.class)
	protected WordsService wordsService;
	@BeanReference(type = WordsPersistence.class)
	protected WordsPersistence wordsPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}