/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.arthurchan35.wcse.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Pages service. Represents a row in the &quot;UrlStorage_Pages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.arthurchan35.wcse.model.impl.PagesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arthurchan35.wcse.model.impl.PagesImpl}.
 * </p>
 *
 * @author Arthur Chan
 * @see Pages
 * @see com.arthurchan35.wcse.model.impl.PagesImpl
 * @see com.arthurchan35.wcse.model.impl.PagesModelImpl
 * @generated
 */
@ProviderType
public interface PagesModel extends BaseModel<Pages> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pages model instance should use the {@link Pages} interface instead.
	 */

	/**
	 * Returns the primary key of this pages.
	 *
	 * @return the primary key of this pages
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pages.
	 *
	 * @param primaryKey the primary key of this pages
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the url_id of this pages.
	 *
	 * @return the url_id of this pages
	 */
	public long getUrl_id();

	/**
	 * Sets the url_id of this pages.
	 *
	 * @param url_id the url_id of this pages
	 */
	public void setUrl_id(long url_id);

	/**
	 * Returns the url of this pages.
	 *
	 * @return the url of this pages
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this pages.
	 *
	 * @param url the url of this pages
	 */
	public void setUrl(String url);

	/**
	 * Returns the description of this pages.
	 *
	 * @return the description of this pages
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this pages.
	 *
	 * @param description the description of this pages
	 */
	public void setDescription(String description);

	/**
	 * Returns the image of this pages.
	 *
	 * @return the image of this pages
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this pages.
	 *
	 * @param image the image of this pages
	 */
	public void setImage(String image);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Pages pages);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Pages> toCacheModel();

	@Override
	public Pages toEscapedModel();

	@Override
	public Pages toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}